### PR TITLE
Fix crash on "empty" request.

### PR DESCRIPTION
**Pull request by AltoRetrato**
Hi again!

Featherweb sometimes stop working after a few requests. Debugging the issue, I noticed that an "empty" request would cause an exception in the HTTPRequest constructor, at `self.method, self.path, self.proto = request.decode().split()`  (since `request` is `b''`). This small patch fix the issue.

### CODE REVIEW

**Comment by jason-richards** [comment]
Hi Ricardo,

I think you may actually be seeing a different issue.  Please check my
latest commits.

Regards,
Jason

**Comment by AltoRetrato** [comment]
I see. Perhaps this patch fix the symptom instead of the cause... yet, it hardens the code, since a simple malformed request can easily crash the server.

**Comment by AltoRetrato** [comment]
Sorry - actually, the patch doesn't harden anything much. :(

I still think the code `self.method, self.path, self.proto = request.decode().split()` is a bit brittle, but I'm not sure the best way to improve it, tough.

**Comment by jason-richards** [comment]
Awesome; thanks for your efforts!  We will get it figured out.  I literally have the server running on a device for months and have never seen the issue.  Can you reproduce the issue with a particular curl request?  Maybe we need to modify readline to accept a timeout value: I had to do something similar to the micropython urequest library.

**Pull request closed without merging**
